### ISSUE TITLE
TypeError: plugin.apply is not a function with v4.0.0

### ISSUE THREAD

**Issue by manastalukdar** [nagaozen/markdown-it-toc-done-right#12]
Running into "TypeError: plugin.apply is not a function" with version 4.0.0.

```text
r TypeError: plugin.apply is not a function
    at MarkdownIt.push../node_modules/markdown-it/lib/index.js.MarkdownIt.use (vendors.._src_components_pages_blog__year__month__day__post.._src_components_pages_index.js:13325)
    at _callee$ (._src_components_pages_blog__year__month__day__post.19e4fd7a250bcd634c5a.hot-update.js:145)
    at tryCatch (commons.app.js:6771)
    at Generator.invoke [as _invoke] (commons.app.js:6997)
    at Generator.prototype.<computed> [as next] (commons.app.js:6823)
    at asyncGeneratorStep (vendors.app.js:31)
    at _next (vendors.app.js:53)
    at vendors.app.js:60
    at new Promise (<anonymous>)
    at vendors.app.js:49
```

Reproducible using [this repo](https://github.com/manastalukdar/manastalukdar.github.io).

**Comment by nagaozen** [comment]
Should be fixed by `4.0.1`. Could you please confirm?

**Comment by manastalukdar** [comment]
Unfortunately same issue manifests with 4.0.1.

**Comment by nagaozen** [comment]
@manastalukdar, cannot reproduce the error. What's needed to run it? I did:

```sh
git clone https://github.com/manastalukdar/manastalukdar.github.io.git
cd manastalukdar.github.io.git
cd website
npm i
npm run nuxt-dev
```
Last command returns this error:

```sh
Cannot find module '../src/static/blogdata/metadata/blog_metadata.json'                                                                       11:10:32
Require stack:
- /run/media/nagaozen/OS/sandbox/manastalukdar.github.io/website/utils/getRoutes.js
- /run/media/nagaozen/OS/sandbox/manastalukdar.github.io/website/nuxt.config.js
- /run/media/nagaozen/OS/sandbox/manastalukdar.github.io/website/node_modules/@nuxt/cli/dist/cli-chunk.js
- /run/media/nagaozen/OS/sandbox/manastalukdar.github.io/website/node_modules/@nuxt/cli/dist/cli.js
- /run/media/nagaozen/OS/sandbox/manastalukdar.github.io/website/node_modules/nuxt/bin/nuxt.js

  Error: Cannot find module '../src/static/blogdata/metadata/blog_metadata.json'
  Require stack:
  - utils/getRoutes.js
  - nuxt.config.js
  - node_modules/@nuxt/cli/dist/cli-chunk.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at Object.<anonymous> (utils/getRoutes.js:1)
```

**Comment by manastalukdar** [comment]
@nagaozen 

Before running `npm run nuxt-dev` you have to run the Python script `scripts/create_blog_metadata.py`. The prerequisite python packages can be installed using the `scripts/python-requirements.txt` file.

**Comment by manastalukdar** [comment]
@nagaozen , Any update?

**Comment by nagaozen** [comment]
This issue is probably related to microbundle as it started appearing after that update. I updated it to the latest version in the last commit. Could you please check if it's fixed now?

**Comment by manastalukdar** [comment]
No luck. Same issue persists with the latest version (4.0.2).

**Comment by nagaozen** [comment]
Do you know what entry from package.json your bundler is using?  Because using main works fine in node.js

**Comment by manastalukdar** [comment]
Fixed by including packages using the `import` statement:

```javascript
import markdownItAnchor from 'markdown-it-anchor'
import markdownItTocDoneRight from 'markdown-it-toc-done-right'

const md = require('markdown-it')
    .use(markdownItAnchor, {
        permalink: true,
        permalinkBefore: true,
        permalinkSymbol: '' // §
      })
    .use(markdownItTocDoneRight)
```
